### PR TITLE
63 step external reference

### LINKED ISSUE #63: Gauge is not able to call step from DLL
Problem Statement:
We have a reusable step which is being used across projects so we thought of packaging it into the DLL and then have projects call this DLL as a reference in there .Net project

### Expected behavior
User should be able to use step in spec file even though the step is in DLL file

### Actual behavior
User is not able to use step if the step is in DLL file. User gets "Step implementation not found" error

### Steps to reproduce
1. Create a new .cs file in .Net. This .cs file should have a step defined in it. It could be any step.
2. Package this .cs file into DLL
3. Add this DLL into your .Net project
4. Create a new spec file
5. Use the step defined in step 1
6. User gets "Step implementation not found" error.

### Gauge version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
json-report (0.3.0)
screenshot (0.0.1)
xml-report (0.2.1)

### PR DESCRIPTION
**Pull request by sriv**
fixes #63 , #51 

Note: IDE authoring support such as goto-def would need to be done separately.

Steps, ScreenshotWriters can be picked up from a DLL/project reference.

### CODE REVIEW

File: src/Processors/StepNameProcessor.cs [hunk 1]
```diff
@@ -43,16 +45,19 @@ public StepNameResponse Process(StepNameRequest request)
             var stepText = _stepRegistry.GetStepText(parsedStepText);
             var hasAlias = _stepRegistry.HasAlias(stepText);
             var info = _stepRegistry.MethodFor(parsedStepText);
-
+            response.IsExternal = info.IsExternal;
             response.HasAlias = hasAlias;
-            response.FileName = info.FileName;
-            response.Span = new Span
+            if (!response.IsExternal)
```
Comment (negiDharmendra) [inline src/Processors/StepNameProcessor.cs]: Please add test for processing external step name request.

Comment (sriv) [reply src/Processors/StepNameProcessor.cs]: @BugDiver - do you want to take a shot at this?

Comment (BugDiver) [reply src/Processors/StepNameProcessor.cs]: There are integration tests covering this scenario. I'll try to add few units as well.
And just now I realize I may have missed one case (StepPositions can be null for external reference), I'll adress that as well.
