### PR TITLE
Unload context after scanning, fixes #114

### LINKED ISSUE #114: Unable to debug the project in vscode as dlls are getting blocked by some other process instantiated by vscode extension
Hi,

I am unable to debug the project because the dlls are getting blocked by some other process initiated by vscode extension. When i kill the process i can debug the code but then intellisense stop working.

PFB the error:
error MSB3021: Unable to copy file "C:\Users\user.nuget\packages\fluentassertions\4.19.4\lib\netstandard1.3\FluentAssertions.Core.dll" to "Sample\gauge_bin\FluentAssertions.Core.dll". The process cannot access the file 'Sample\gauge_bin\FluentAssertions.Core.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". Exceeded r
etry count of 10. Failed. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". The process cannot access the file 'Sample\gauge_bin\netcore-template.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "C:\Users\user.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". Exceeded retry count of 10. Failed. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "C:\Users\user.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". The process cannot access the file 'Sample\gauge_bin\Gauge.CSharp.Lib.dll' because it is being used by another process. [Sample\netcore-template.csproj]
{"logLevel":"fatal","message":"Unable to build Project in Sample\ndotnet Project build failed.\nRan 'dotnet publish --runtime=win-x64 --configuration=Debug --output="Sample\gauge_bin" "netcore-template.csproj" --verbosit
y=quiet'\n at Gauge.Dotnet.GaugeProjectBuilder.BuildTargetGaugeProject()\r\n at Gauge.Dotnet.StartCommand.TryBuild()"}

Gauge version: 1.1.3
Commit Hash: 9d3a3d5

Plugins
-------
dotnet (0.1.7)
html-report (4.0.8)
screenshot (0.0.1)

### PR DESCRIPTION
**Pull request by sriv**
Fix for #114

Since 0.1.7, gauge-dotnet loads target assemblies in a custom load context, and this causes the assemblies to be locked.

Maring the `GaugeLoadContext` as `collectible` and invoking `Unload` after scan releases the assemblies. However, this has an undesirable sideeffect when running specs. The reflected types and methods are not available at time of running.

This PR checks if gauge-dotnet is used to power LanguageServer and conditionally marks `GaugeLoadContext` as collectible, and invokes `Unload`.

### CODE REVIEW

File: src/GaugeLoadContext.cs [hunk 1]
```diff
@@ -11,15 +11,25 @@
...
 namespace Gauge.Dotnet
 {
-    public class GaugeLoadContext: AssemblyLoadContext, IGaugeLoadContext {
+    public class GaugeLoadContext: AssemblyLoadContext, IGaugeLoadContext, System.IDisposable
+    {
         private const string GaugeLibAssemblyName = "Gauge.CSharp.Lib";
         private AssemblyDependencyResolver _resolver;
 
-        public GaugeLoadContext(string pluginPath)
+        public GaugeLoadContext(string pluginPath, bool collectibe = false) : base(collectibe)
```
Comment (BugDiver) [inline src/GaugeLoadContext.cs:19]: Typo in `base(collectibe)`

**Review by BugDiver — CHANGES_REQUESTED** [review]

File: src/GaugeLoadContext.cs (hunk 1 above)
Comment (sriv) [reply src/GaugeLoadContext.cs]: fixed.

**Review by BugDiver — APPROVED** [review]
